/* Inlines PNGs into index.html at a named slot.
 *
 *     node tools/inline-asset.mjs BACKDROP assets/backdrop.png
 *     node tools/inline-asset.mjs CINDU assets/cindu-0.png assets/cindu-1.png assets/cindu-2.png
 *
 * The game reads the inlined copies, never the files on disk -- that is what
 * keeps "one HTML file, double-click to play" true. The files under assets/
 * are the editable masters; this is the build step that ships them.
 *
 * Not everything is inlined. Boss art loads from assets/bosses/ at runtime
 * because ten of them would be megabytes; see docs/ASSET-PIPELINE.md. Inlining
 * is for the handful of assets that are always on screen.
 *
 * Slots are marked in index.html as:
 *
 *     [comment] ==== NAME:BEGIN ... ==== [end comment]
 *     const NAME_PNG = ...;
 *     [comment] ==== NAME:END ==== [end comment]
 *
 * One file emits a string; several emit an array, in the order given.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

/* Per-slot budget in KB, per file. These are not arbitrary: the backdrop is a
   dim silhouette that needs no detail, and Cindu is three frames, so her
   budget is a third of what a single sprite could afford. */
const SLOTS = {
  BACKDROP: { files: 1, budgetKB: 150, constName: 'BACKDROP_PNG' },
  CINDU:    { files: 3, budgetKB: 120, constName: 'CINDU_PNG' },
};

const [slot, ...pngArgs] = process.argv.slice(2);
const spec = SLOTS[slot];
const clearing = pngArgs[0] === '--clear';

if (!spec){
  console.error(`usage: node tools/inline-asset.mjs <SLOT> <file.png...>`);
  console.error(`       node tools/inline-asset.mjs <SLOT> --clear`);
  console.error(`slots: ${Object.keys(SLOTS).map(s => `${s} (${SLOTS[s].files} file${SLOTS[s].files > 1 ? 's' : ''})`).join(', ')}`);
  process.exit(1);
}
if (!clearing && pngArgs.length !== spec.files){
  console.error(`error: ${slot} takes exactly ${spec.files} file(s), got ${pngArgs.length}.`);
  process.exit(1);
}

const htmlPath = resolve('index.html');
const BEGIN = `/* ==== ${slot}:BEGIN`;
const END   = `/* ==== ${slot}:END ==== */`;

const pngs = clearing ? [] : pngArgs.map(a => {
  const p = resolve(a);
  const buf = readFileSync(p);
  if (buf.subarray(0, 8).toString('hex') !== '89504e470d0a1a0a'){
    console.error(`error: ${a} is not a PNG.`);
    process.exit(1);
  }
  return { path: a, buf };
});

let html = readFileSync(htmlPath, 'utf8');
const i = html.indexOf(BEGIN);
const j = html.indexOf(END);
if (i < 0 || j < 0 || j < i){
  console.error(`error: could not find the ${slot}:BEGIN/END markers in index.html.`);
  process.exit(1);
}

/* Clearing writes the empty shape the slot has when no art exists, which the
   loader reads as "draw vectors". Use it to revert to the vector renderer
   without hand-editing a 400KB line. */
const uri = b => `'data:image/png;base64,${b.toString('base64')}'`;
const empty = spec.files === 1 ? "''" : `[${Array(spec.files).fill("''").join(', ')}]`;
const value = clearing ? empty
  : pngs.length === 1 ? uri(pngs[0].buf)
  : `[\n  ${pngs.map(p => uri(p.buf)).join(',\n  ')},\n]`;

const block =
  `${BEGIN} (generated by tools/inline-asset.mjs -- do not hand-edit) ==== */\n` +
  `const ${spec.constName} = ${value};\n` +
  END;

const before = html.length;
html = html.slice(0, i) + block + html.slice(j + END.length);
writeFileSync(htmlPath, html);

console.log(clearing ? `cleared ${slot} -- the vector renderer draws it now` : `inlined ${slot}`);
for (const p of pngs) console.log(`  ${p.path}  ${(p.buf.length/1024).toFixed(1)}KB`);
console.log(`  index.html  ${(before/1024).toFixed(1)}KB -> ${(html.length/1024).toFixed(1)}KB`);

const over = pngs.filter(p => p.buf.length/1024 > spec.budgetKB);
if (over.length){
  console.warn(`\nwarning: ${over.length} file(s) over the ${spec.budgetKB}KB budget for ${slot}:`);
  for (const p of over) console.warn(`  ${p.path}  ${(p.buf.length/1024).toFixed(1)}KB`);
  console.warn('Every inlined byte is paid on first load by every player. Try a lower');
  console.warn('resolution, fewer colours, or more fully-transparent area.');
}
